### PR TITLE
Feature/standard documented endpoints

### PR DESCRIPTION
**Pull request by MTaylor-tech**
Full swagger documentation for workOrder and user endpoints. Fixed some bugs in the workOrder model. Standardized the workOrder endpoints. Once merged, documentation will appear at [https://xcel-wom-api-b.herokuapp.com/api-docs/](https://xcel-wom-api-b.herokuapp.com/api-docs/)
On local machine, use: [http://127.0.0.1/api-docs](http://127.0.0.1/api-docs)

### CODE REVIEW

**Comment by MTaylor-tech** [comment]
[As IT, I would like standardized and documented API endpoints](https://trello.com/c/7ABJffJj/22-as-it-i-would-like-standardized-and-documented-api-endpoints)

**Comment by MTaylor-tech** [comment]
[As IT, I would like standardized and documented API endpoints](https://trello.com/c/7ABJffJj/22-as-it-i-would-like-standardized-and-documented-api-endpoints)

**Review by Cireimu — APPROVED** [review]
Looks good, documentation looks like it's all put together and the more standardized endpoints streamline things in a manner that should hopefully lead to fewer conflicts and a generally more easy to understand endpoint layout.

**Review by hoangvu71 — APPROVED** [review]
Docs looks great. This will definitely help the front-end team a lot. The only thing that I can think of is smaller and more frequent commits.

**Pull request merged**
