### PR TITLE
database migrations

### PR DESCRIPTION
**Pull request by MTaylor-tech**
all migrations written to bring the database in line with our planned schema (as on Whimsical)

### CODE REVIEW

**Comment by MTaylor-tech** [comment]
[As IT, I would like to create a data schema table so that my data from the work orders are organized](https://trello.com/c/5Lt7i9pX/10-as-it-i-would-like-to-create-a-data-schema-table-so-that-my-data-from-the-work-orders-are-organized)

**Comment by josesustaita** [comment]
Should we add imageurl in the work order table too, I can see you have it in place for the properties table? On the General work order form I am working on it does have a section to add an attachment right from there.

**Review by Cireimu — APPROVED** [review]
Looks good to me, some syntax is a bit odd to me, but everything seems to work and the tables seem to fit in line with what we need. The only other thing I'd add is the imageUrl/attachments field to the work order table.

**Comment by MTaylor-tech** [comment]
> Should we add imageurl in the work order table too, I can see you have it in place for the properties table? On the General work order form I am working on it does have a section to add an attachment right from there.

When we work out how that info is being sent to the back-end, I'll make sure the model pushes attachments into the "image" table. That way, a workOrder can have many images.

**Review by josesustaita — APPROVED** [review]
Looks great! Disregard my last comment. If Postgres is troublesome about having the image under the work order table then having the data schema built out like this is fine.

**Pull request merged**
